name: Manually Publish Python 🐍 distributions 📦 to PyPI

on:
  workflow_dispatch:

jobs:
  build-n-publish:
    if: github.repository == 'joniumGit/headers'
    name: Build, Test and Publish Python 🐍 distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Commit changes and tag release
        run: |
          python tag.py
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
